# Generated by Django 2.1.5 on 2019-05-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnterApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(max_length=5, verbose_name='铺位ID')),
                ('lease_id', models.CharField(max_length=10, verbose_name='租约ID')),
                ('user_id', models.CharField(max_length=6, verbose_name='用户ID')),
                ('deadline', models.DateTimeField(verbose_name='租用期限')),
                ('applicate_date', models.DateTimeField(verbose_name='申请日期')),
                ('review_date', models.DateTimeField(verbose_name='审阅日期')),
                ('review_status', models.CharField(max_length=6, verbose_name='审阅情况')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loacate', models.CharField(max_length=10, unique=True, verbose_name='店铺位置(x层y号)')),
                ('area', models.CharField(max_length=10, verbose_name='店铺面积')),
                ('rent', models.CharField(max_length=10, verbose_name='店铺租金')),
                ('status', models.CharField(max_length=2, verbose_name='铺位情况(租-0\\闲-1\\修-2)')),
            ],
        ),
    ]
