# Generated by Django 2.1.5 on 2019-05-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forlease', '0002_auto_20190525_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=10, verbose_name='用户类型')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号码')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('idCard', models.CharField(max_length=18, verbose_name='身份证')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('email', models.CharField(max_length=320, verbose_name='邮箱')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AlterField(
            model_name='enterapplication',
            name='lease_id',
            field=models.IntegerField(verbose_name='租约ID'),
        ),
        migrations.AlterField(
            model_name='enterapplication',
            name='unit_id',
            field=models.IntegerField(verbose_name='铺位ID'),
        ),
        migrations.AlterField(
            model_name='enterapplication',
            name='user_id',
            field=models.IntegerField(verbose_name='用户ID'),
        ),
        migrations.AlterModelTable(
            name='enterapplication',
            table='enter_application',
        ),
        migrations.AlterModelTable(
            name='unit',
            table='unit',
        ),
    ]
