# Generated by Django 2.1.5 on 2019-05-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeferPayApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_id', models.IntegerField(verbose_name='租约ID')),
                ('original_date', models.DateTimeField(verbose_name='原支付日期')),
                ('current_date', models.DateTimeField(verbose_name='现支付日期')),
                ('apply_date', models.DateTimeField(verbose_name='申请日期')),
                ('handle_date', models.DateTimeField(verbose_name='处理日期')),
                ('status', models.CharField(max_length=10, verbose_name='审阅情况')),
            ],
            options={
                'db_table': 'defer_pay_application',
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('name', models.CharField(max_length=20, verbose_name='店铺名称')),
                ('rent', models.CharField(max_length=10, verbose_name='租金')),
                ('duration', models.CharField(max_length=10, verbose_name='持续时间')),
                ('start_date', models.DateTimeField(verbose_name='起效时间')),
            ],
            options={
                'db_table': 'lease',
            },
        ),
        migrations.CreateModel(
            name='Paymemt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_id', models.IntegerField(verbose_name='租约ID')),
                ('payer_id', models.IntegerField(verbose_name='支付者ID')),
                ('pay_amount', models.FloatField(verbose_name='支付金额')),
                ('pay_date', models.DateTimeField(verbose_name='支付时间')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='RefundApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('rent_id', models.IntegerField(verbose_name='租约ID')),
                ('default_value', models.FloatField(verbose_name='违约金')),
                ('apply_date', models.DateTimeField(verbose_name='申请时间')),
                ('handle_date', models.DateTimeField(verbose_name='处理时间')),
                ('status', models.CharField(max_length=10, verbose_name='审阅情况')),
            ],
            options={
                'db_table': 'refund_application',
            },
        ),
    ]
