# Generated by Django 2.1.5 on 2019-05-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.IntegerField(verbose_name='设施ID')),
                ('status', models.CharField(max_length=10, verbose_name='检查情况')),
                ('check_date', models.DateTimeField(verbose_name='检查日期')),
                ('user_id', models.IntegerField(verbose_name='检查者ID')),
            ],
            options={
                'db_table': 'check_record',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(max_length=10, verbose_name='设施类型')),
                ('facility_name', models.CharField(max_length=10, verbose_name='设施名字')),
                ('location', models.CharField(max_length=10, verbose_name='位置')),
                ('deadline', models.DateTimeField(verbose_name='失效期')),
            ],
            options={
                'db_table': 'facility',
            },
        ),
    ]
